import { IFilterCreate } from '@/shared/types/filters.types';

export const createFilterDefault: IFilterCreate = {
  idCities: [],
  devicetoken: '',
  name: '',
  years: [0, 0],
  prices: [0, 0],
  horsepower: [0, 0],
  mileages: [0, 0],
  marks: [],
  models: [],
  states: [],
  transmissions: [],
  wheels: [],
  regions: [],
  sites: [],
  secondhand: 0,
  notifications: false,
  enabled: false,
  ices: [],
  gears: [],
  owners: 0,
  bodies: [],
  avgCostDeviation: 0,
  iceValues: [],
  cities: '',
  ownerType: 0,
  priceTypes: [],
  carState: 0,
  carTypes: [],
  avgPriceDelta: [0, 0],
  ownersCount: [],
  FilterVersion: '',
  credateTimeStamp: 0,
  credateString: '',
  pricechanges: [0],
  minPricechange: 0,
  idCity: 0,
  cityName: '',
  distance: 0,
};
